const mongoose = require("mongoose");

const registrationSchema = new mongoose.Schema({
  course: { type: String, required: true },
  firstName: { type: String, required: true },
  lastName: String,
  gender: { type: String, required: true },
  category: String,
  dob: { type: String, required: true },
  nationality: String,
  religion: String,
  aadhar: String,
  phone: { type: String, required: true },
  email: { type: String, required: true },
  address: String,
  zip: String,
  state: String,
  city: String,
  fatherName: String,
  fatherContact: String,
  motherName: String,
  motherContact: String,
  highSchoolYear: String,
  highSchoolRoll: String,
  highSchoolBoard: String,
  highSchoolMarks: String,
  highSchoolPercentage: String,
  highSchoolGrade: String,
  highSchoolSubject: String,
  intermediateYear: String,
  intermediateRoll: String,
  intermediateBoard: String,
  intermediateMarks: String,
  intermediatePercentage: String,
  intermediateGrade: String,
  intermediateSubject: String,
  graduationYear: String,
  graduationRoll: String,
  graduationBoard: String,
  graduationMarks: String,
  graduationPercentage: String,
  graduationGrade: String,
  graduationSubject: String,
  termsAgreed: { type: Boolean, required: true },
  verificationCode: String,
  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("Registration", registrationSchema);
